//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSULTORIO_CON_SQLITE.GeneradorDePDF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CONSULTORIO_CON_SQLITE.GeneradorDePDF.HtmlTemplates", typeof(HtmlTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;service&quot;&gt; {0} &lt;/tr&gt;.
        /// </summary>
        public static string BodyContainer {
            get {
                return ResourceManager.GetString("BodyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class=&quot;tableitem&quot;&gt; &lt;p class=&quot;itemtext&quot;&gt; {0} &lt;/p&gt;&lt;/td&gt;.
        /// </summary>
        public static string BodyValues {
            get {
                return ResourceManager.GetString("BodyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;legalcopy&quot;&gt; &lt;p class=&quot;legal&quot;&gt; {0} &lt;/p&gt;&lt;/div&gt;.
        /// </summary>
        public static string FooterCredits {
            get {
                return ResourceManager.GetString("FooterCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt; &lt;h2&gt; {0} &lt;/h2&gt; &lt;/td&gt;.
        /// </summary>
        public static string HeaderValues {
            get {
                return ResourceManager.GetString("HeaderValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt; &lt;div class=&quot;logotype&quot;&gt; &lt;/div&gt; &lt;h2 class=&quot;logotype&quot;&gt; {0} &lt;/h2&gt; &lt;/div&gt;.
        /// </summary>
        public static string LogotextTop {
            get {
                return ResourceManager.GetString("LogotextTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;mid&quot;&gt; &lt;div class=&quot;info&quot;&gt; &lt;h2&gt; {0} &lt;/h2&gt; &lt;p&gt;{1}&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string MidInfo {
            get {
                return ResourceManager.GetString("MidInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt; &lt;title&gt; Report &lt;/title&gt; {3} &lt;/head&gt;&lt;body&gt; &lt;div id=&quot;invoice-POS&quot;&gt;{0} {1} {2}  &lt;/div&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string TheContainer {
            get {
                return ResourceManager.GetString("TheContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt; #invoice-POS{box-shadow: 0 0 1in -0.25in rgba(0, 0, 0, 0.5); padding: 2mm; margin: 0 auto; width: 80%; background: #FFF;}h1{font-size: 2.5em; color: #222;}h2{font-size: .9em;}h3{font-size: 1.2em; font-weight: 300; line-height: 2em;}p{font-size: .7em; color: #666; line-height: 1.2em;}#top, #mid, #bot{/* Targets all id with &apos;col-&apos; */ border-bottom: 1px solid #EEE;}#top{min-height: 10%;}#mid{min-height: 10%; margin-top: 70px;}#bot{min-height: 50%;}.info{display: block; margin-left: 0;}. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TheStyles {
            get {
                return ResourceManager.GetString("TheStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;bot&quot;&gt; &lt;div id=&quot;table&quot;&gt; &lt;table&gt; {0} {1} &lt;/table&gt; &lt;/div&gt; {2} &lt;/div&gt;.
        /// </summary>
        public static string TheTable {
            get {
                return ResourceManager.GetString("TheTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;tabletitle&quot;&gt; {0} &lt;/tr&gt;.
        /// </summary>
        public static string TitleContainer {
            get {
                return ResourceManager.GetString("TitleContainer", resourceCulture);
            }
        }
    }
}
